language: java
jdk:
  - openjdk11

before_install:
  - export CORRETTO_VERSION=$(curl -s https://corretto.aws/[latest/latest_checksum]/ | grep -o 'amazon-corretto-17.*-linux-jdk.tar.gz' | cut -d'-' -f3)
  - export CORRETTO_CHECKSUM_URL="https://corretto.aws/[latest/latest_checksum]/${CORRETTO_VERSION}/amazon-corretto-${CORRETTO_VERSION}-x64-linux-jdk.tar.gz"
  - export CORRETTO_TAR_FILE="/tmp/amazon-corretto-${CORRETTO_VERSION}-x64-linux-jdk.tar.gz"
  - wget -O $CORRETTO_TAR_FILE $CORRETTO_CHECKSUM_URL
  - tar xvf $CORRETTO_TAR_FILE
  - export JAVA_HOME=/tmp/amazon-corretto-${CORRETTO_VERSION}-x64-linux-jdk
  - export PATH=$JAVA_HOME/bin:$PATH
  
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

addons:
  sonarcloud:
    organization: "ssilvestri15"
    token:
      secure: "EtwfcmV8LYLT1hEet1sgS0jcWTdcgIfDtjKwp899n6M+Q2FBQNitqzdmxPkRUeY290bmF6s03hsVViyJvXQDyNgwmzwOcGGuUJIcK7/TsSHDBgu1wymzpDqKN5hDQsrCdI0vClAnhO5aQ11vX6qRZU4ng464/2pFd4prZq+qx8HouaVFArvZGy7JptUu7iZshVApHRvjZ50mJHyIVIeZkfBK4Yleq0UWNPVRWXqHNsXFZeYj5sHttZPmjEbWn/4PrPAC7tNn9KSI3Y/sHa4ZlTpZJXcOsj4yBq/J5uzdJ+1hbT0g65xb4WGSrO3J7vcUE2DTLsTzI9GfWgq+dEuZ/Sv69Si5r1Ya8ekGvBlAjLoLWu2itIaoxrmvTUy34jaqPE0nePyRL578AC3cYoLeNCUHVcl/Y6+gN3bEuAmYinf4wBw6N2BQxFGIoUuae+y9Cd/WDIU2PWxK9PsKc1z+hDlYZ2+8TV3I3wlGtIRgsyZFrYKn1oildJh4N7abQspme3UHFvvgMK2CIMvscs1iLy17ehp+yBtAZspFBsLeDA2d++/BXZIgFDpAPQiegVt7RvE4wJehgTvCrH02kjGoyPzaTqRLZmDfwHEpLcCToRIvMuO1aSVnyZBhVN8mdNqU5aRgMpPdPyNayvMywUIj/OqnoKurEnZYIy6hTls+Rk8="


script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ssilvestri15_ebalance_c17